[project]
name = "controlled-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keras>=3.10.0",
    "matplotlib>=3.10.3",
]
